'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

import type {
  AutoScheduleShiftRow,
  AvailabilityOverrideRow,
  ShiftLimitRow,
  Therapist,
} from '@/app/schedule/types'
import { can } from '@/lib/auth/can'
import { writeAuditLog } from '@/lib/audit-log'
import { insertAutoGeneratedShifts } from '@/lib/coverage/auto-generated-shifts'
import { generateDraftForCycle } from '@/lib/coverage/generate-draft'
import { NO_ELIGIBLE_CANDIDATES_REASON } from '@/lib/coverage/generator-slot'
import { normalizeWorkPattern, type WorkPattern } from '@/lib/coverage/work-patterns'
import { buildDateRange, buildScheduleUrl, getWeekBoundsForDate } from '@/lib/schedule-helpers'
import { setDesignatedLeadMutation } from '@/lib/set-designated-lead'
import { createClient } from '@/lib/supabase/server'

import { buildCoverageUrl, getRoleForUser } from './helpers'

export async function generateDraftScheduleAction(formData: FormData) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  const role = await getRoleForUser(user.id)
  if (!can(role, 'manage_schedule')) {
    redirect('/schedule')
  }

  const cycleId = String(formData.get('cycle_id') ?? '').trim()
  const view = String(formData.get('view') ?? '').trim()
  const returnTo = String(formData.get('return_to') ?? '').trim()
  const showUnavailable = String(formData.get('show_unavailable') ?? '').trim() === 'true'
  const viewParams = showUnavailable ? { show_unavailable: 'true' } : undefined
  const buildReturnUrl = (
    cycleIdOverride: string | undefined,
    params?: Record<string, string | undefined>
  ) =>
    returnTo === 'coverage'
      ? buildCoverageUrl(cycleIdOverride, params)
      : buildScheduleUrl(cycleIdOverride, view, params)

  if (!cycleId) {
    redirect(buildReturnUrl(undefined, { ...viewParams, error: 'auto_missing_cycle' }))
  }

  const { data: cycle, error: cycleError } = await supabase
    .from('schedule_cycles')
    .select('id, start_date, end_date, published')
    .eq('id', cycleId)
    .maybeSingle()

  if (cycleError || !cycle) {
    console.error('Failed to load cycle for auto-generation:', cycleError)
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_failed' }))
  }

  if (cycle.published) {
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_cycle_published' }))
  }

  const { data: therapistsData, error: therapistsError } = await supabase
    .from('profiles')
    .select(
      'id, full_name, shift_type, is_lead_eligible, employment_type, max_work_days_per_week, on_fmla, fmla_return_date, is_active'
    )
    .in('role', ['therapist', 'lead'])
    .order('full_name', { ascending: true })

  if (therapistsError) {
    console.error('Failed to load therapists for auto-generation:', therapistsError)
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_failed' }))
  }

  const rawTherapists = (therapistsData ?? []) as Array<{
    id: string
    full_name: string
    shift_type: 'day' | 'night'
    is_lead_eligible: boolean
    employment_type: 'full_time' | 'part_time' | 'prn'
    max_work_days_per_week: number
    on_fmla: boolean
    fmla_return_date: string | null
    is_active: boolean
  }>
  const therapistIds = rawTherapists.map((therapist) => therapist.id)

  const { data: workPatternsData, error: workPatternsError } = therapistIds.length
    ? await supabase
        .from('work_patterns')
        .select(
          'therapist_id, pattern_type, works_dow, offs_dow, weekend_rotation, weekend_anchor_date, works_dow_mode, weekly_weekdays, weekend_rule, cycle_anchor_date, cycle_segments, shift_preference'
        )
        .in('therapist_id', therapistIds)
    : { data: [], error: null }

  if (workPatternsError) {
    console.error('Failed to load work patterns for auto-generation:', workPatternsError)
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_failed' }))
  }

  const patternByTherapist = new Map(
    (
      (workPatternsData ?? []) as Array<{
        therapist_id: string
        pattern_type: WorkPattern['pattern_type'] | null
        works_dow: number[] | null
        offs_dow: number[] | null
        weekend_rotation: 'none' | 'every_other' | null
        weekend_anchor_date: string | null
        works_dow_mode: 'hard' | 'soft' | null
        weekly_weekdays: number[] | null
        weekend_rule: WorkPattern['weekend_rule'] | null
        cycle_anchor_date: string | null
        cycle_segments: WorkPattern['cycle_segments'] | null
        shift_preference: 'day' | 'night' | 'either' | null
      }>
    ).map((row) => [
      row.therapist_id,
      normalizeWorkPattern({
        therapist_id: row.therapist_id,
        pattern_type: row.pattern_type ?? undefined,
        works_dow: row.works_dow ?? [],
        offs_dow: row.offs_dow ?? [],
        weekend_rotation: row.weekend_rotation ?? undefined,
        weekend_anchor_date: row.weekend_anchor_date,
        works_dow_mode: row.works_dow_mode ?? undefined,
        weekly_weekdays: row.weekly_weekdays ?? row.works_dow ?? [],
        weekend_rule: row.weekend_rule ?? undefined,
        cycle_anchor_date: row.cycle_anchor_date ?? null,
        cycle_segments: row.cycle_segments ?? [],
        shift_preference: row.shift_preference ?? 'either',
      }),
    ])
  )

  const therapists: Therapist[] = rawTherapists.map((therapist) => {
    const pattern =
      patternByTherapist.get(therapist.id) ??
      normalizeWorkPattern({
        therapist_id: therapist.id,
        works_dow: [0, 1, 2, 3, 4, 5, 6],
        offs_dow: [],
        weekend_rotation: 'none',
        weekend_anchor_date: null,
        works_dow_mode: 'hard',
        shift_preference: 'either',
      })
    return {
      ...therapist,
      works_dow: [0, 1, 2, 3, 4, 5, 6],
      offs_dow: [],
      weekend_rotation: 'none',
      weekend_anchor_date: null,
      works_dow_mode: 'hard',
      pattern,
      shift_preference: pattern.shift_preference,
    }
  })
  if (therapists.length === 0) {
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_no_therapists' }))
  }

  const cycleDates = buildDateRange(cycle.start_date, cycle.end_date)
  if (cycleDates.length === 0) {
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_failed' }))
  }

  const firstWeekBounds = getWeekBoundsForDate(cycle.start_date)
  const lastWeekBounds = getWeekBoundsForDate(cycle.end_date)
  if (!firstWeekBounds || !lastWeekBounds) {
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_failed' }))
  }

  const { error: clearUnfilledReasonError } = await supabase
    .from('shifts')
    .delete()
    .eq('cycle_id', cycleId)
    .not('unfilled_reason', 'is', null)

  if (clearUnfilledReasonError) {
    console.error('Failed to clear prior unfilled reason placeholders:', clearUnfilledReasonError)
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_failed' }))
  }

  const [existingShiftsResult, cycleOverridesResult, weeklyShiftsResult] = await Promise.all([
    supabase
      .from('shifts')
      .select('user_id, date, shift_type, status, role, unfilled_reason')
      .eq('cycle_id', cycleId),
    supabase
      .from('availability_overrides')
      .select('therapist_id, cycle_id, date, shift_type, override_type, note, source')
      .eq('cycle_id', cycleId)
      .gte('date', cycle.start_date)
      .lte('date', cycle.end_date),
    supabase
      .from('shifts')
      .select('user_id, date, status')
      .in('user_id', therapistIds)
      .gte('date', firstWeekBounds.weekStart)
      .lte('date', lastWeekBounds.weekEnd),
  ])

  if (existingShiftsResult.error || cycleOverridesResult.error || weeklyShiftsResult.error) {
    console.error('Failed to load scheduling data for auto-generation:', {
      existingShiftsError: existingShiftsResult.error,
      cycleOverridesError: cycleOverridesResult.error,
      weeklyShiftsError: weeklyShiftsResult.error,
    })
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_failed' }))
  }

  const existingShifts = (
    (existingShiftsResult.data ?? []) as Array<
      AutoScheduleShiftRow & { unfilled_reason?: string | null; user_id: string | null }
    >
  ).filter((row) => Boolean(row.user_id) && !row.unfilled_reason) as AutoScheduleShiftRow[]
  const allAvailabilityOverrides = (cycleOverridesResult.data ?? []) as AvailabilityOverrideRow[]

  const {
    draftShiftsToInsert,
    pendingLeadUpdates,
    unfilledConstraintSlots,
    unfilledSlots,
    constraintsUnfilledSlots,
    missingLeadSlots,
    forcedMustWorkMisses,
  } = generateDraftForCycle({
    cycleId,
    cycleStartDate: cycle.start_date,
    cycleEndDate: cycle.end_date,
    therapists,
    existingShifts,
    allAvailabilityOverrides,
    weeklyShifts: (weeklyShiftsResult.data ?? []) as ShiftLimitRow[],
  })

  if (draftShiftsToInsert.length > 0) {
    const insertResult = await insertAutoGeneratedShifts(supabase, draftShiftsToInsert)

    if (insertResult.error && !insertResult.duplicateConflict) {
      console.error('Failed to insert auto-generated shifts:', insertResult.error)
      redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_db_error' }))
    }

    if (insertResult.duplicateConflict) {
      console.warn(
        'Auto-generate encountered concurrent duplicate shifts; draft may be incomplete.'
      )
      redirect(
        buildReturnUrl(cycleId, {
          ...viewParams,
          error: 'auto_generate_coverage_incomplete',
          dropped: String(draftShiftsToInsert.length),
        })
      )
    }

    const silentlyDropped = draftShiftsToInsert.length - insertResult.insertedCount
    if (silentlyDropped > 0) {
      console.warn(
        `Auto-generate: ${silentlyDropped} shift(s) skipped due to concurrent conflicts.`
      )
      redirect(
        buildReturnUrl(cycleId, {
          ...viewParams,
          error: 'auto_generate_coverage_incomplete',
          dropped: String(silentlyDropped),
        })
      )
    }
  }

  if (unfilledConstraintSlots.length > 0) {
    const unfilledReasonRows = unfilledConstraintSlots.map((slot) => ({
      cycle_id: cycleId,
      user_id: null,
      date: slot.date,
      shift_type: slot.shiftType,
      status: 'called_off' as const,
      assignment_status: 'cancelled' as const,
      role: 'staff' as const,
      unfilled_reason: NO_ELIGIBLE_CANDIDATES_REASON,
      status_note: `Missing ${slot.missingCount} required assignment${slot.missingCount === 1 ? '' : 's'} due to hard constraints.`,
    }))

    const { error: unfilledInsertError } = await supabase.from('shifts').insert(unfilledReasonRows)

    if (unfilledInsertError) {
      console.error('Failed to record unfilled constraint reasons:', unfilledInsertError)
      redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_db_error' }))
    }
  }

  if (pendingLeadUpdates.length > 0) {
    for (const update of pendingLeadUpdates) {
      const leadResult = await setDesignatedLeadMutation(supabase, {
        cycleId,
        therapistId: update.therapistId,
        date: update.date,
        shiftType: update.shiftType,
      })
      if (!leadResult.ok) {
        console.error('Auto-generate failed to designate lead for slot:', update, leadResult.error)
        redirect(
          buildReturnUrl(cycleId, { ...viewParams, error: 'auto_generate_lead_assignment_failed' })
        )
      }
    }
  }

  await writeAuditLog(supabase, {
    userId: user.id,
    action: 'draft_schedule_generated',
    targetType: 'schedule_cycle',
    targetId: cycleId,
  })

  revalidatePath('/schedule')
  revalidatePath('/coverage')
  redirect(
    buildReturnUrl(cycleId, {
      ...viewParams,
      auto: 'generated',
      added: String(draftShiftsToInsert.length),
      unfilled: String(unfilledSlots),
      constraints_unfilled: String(constraintsUnfilledSlots),
      lead_missing: String(missingLeadSlots),
      forced_misses: forcedMustWorkMisses > 0 ? String(forcedMustWorkMisses) : undefined,
    })
  )
}

export async function resetDraftScheduleAction(formData: FormData) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  const role = await getRoleForUser(user.id)
  if (!can(role, 'manage_schedule')) {
    redirect('/schedule')
  }

  const cycleId = String(formData.get('cycle_id') ?? '').trim()
  const view = String(formData.get('view') ?? '').trim()
  const returnTo = String(formData.get('return_to') ?? '').trim()
  const showUnavailable = String(formData.get('show_unavailable') ?? '').trim() === 'true'
  const viewParams = showUnavailable ? { show_unavailable: 'true' } : undefined
  const buildReturnUrl = (
    cycleIdOverride: string | undefined,
    params?: Record<string, string | undefined>
  ) =>
    returnTo === 'coverage'
      ? buildCoverageUrl(cycleIdOverride, params)
      : buildScheduleUrl(cycleIdOverride, view, params)

  if (!cycleId) {
    redirect(buildReturnUrl(undefined, { ...viewParams, error: 'reset_missing_cycle' }))
  }

  const { data: cycle, error: cycleError } = await supabase
    .from('schedule_cycles')
    .select('id, published')
    .eq('id', cycleId)
    .maybeSingle()

  if (cycleError || !cycle) {
    console.error('Failed to load cycle for reset:', cycleError)
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'reset_failed' }))
  }

  if (cycle.published) {
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'reset_cycle_published' }))
  }

  const { data: deletedRows, error: deleteError } = await supabase
    .from('shifts')
    .delete()
    .eq('cycle_id', cycleId)
    .select('id')

  if (deleteError) {
    console.error('Failed to reset draft shifts:', deleteError)
    redirect(buildReturnUrl(cycleId, { ...viewParams, error: 'reset_failed' }))
  }

  const removedCount = deletedRows?.length ?? 0

  revalidatePath('/schedule')
  revalidatePath('/coverage')
  redirect(
    buildReturnUrl(cycleId, {
      ...viewParams,
      draft: 'reset',
      removed: String(removedCount),
    })
  )
}
