'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

import { can } from '@/lib/auth/can'
import { applyTemplateToCycle, type TemplateShiftData } from '@/lib/cycle-template'
import { insertAutoGeneratedShifts } from '@/lib/coverage/auto-generated-shifts'
import { createClient } from '@/lib/supabase/server'

import { buildCoverageUrl, getRoleForUser } from './helpers'

export async function applyTemplateAction(formData: FormData) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  const role = await getRoleForUser(user.id)
  if (!can(role, 'manage_schedule')) {
    redirect('/schedule')
  }

  const templateId = String(formData.get('template_id') ?? '').trim()
  const cycleId = String(formData.get('new_cycle_id') ?? '').trim()
  const cycleStartDate = String(formData.get('new_cycle_start_date') ?? '').trim()

  if (!templateId || !cycleId || !cycleStartDate) {
    redirect(buildCoverageUrl(cycleId || undefined, { error: 'template_apply_failed' }))
  }

  const [{ data: template, error: templateError }, { data: cycle, error: cycleError }] =
    await Promise.all([
      supabase.from('cycle_templates').select('id, shift_data').eq('id', templateId).maybeSingle(),
      supabase
        .from('schedule_cycles')
        .select('id, start_date, published')
        .eq('id', cycleId)
        .maybeSingle(),
    ])

  if (templateError || !template || cycleError || !cycle || cycle.published) {
    redirect(buildCoverageUrl(cycleId, { error: 'template_apply_failed' }))
  }

  const templateData = (
    Array.isArray(template.shift_data) ? template.shift_data : []
  ) as TemplateShiftData[]
  const templateUserIds = [...new Set(templateData.map((row) => row.user_id))]

  const { data: activeProfiles, error: activeProfilesError } =
    templateUserIds.length > 0
      ? await supabase
          .from('profiles')
          .select('id')
          .in('id', templateUserIds)
          .in('role', ['therapist', 'lead'])
          .eq('is_active', true)
          .is('archived_at', null)
      : { data: [], error: null }

  if (activeProfilesError) {
    redirect(buildCoverageUrl(cycleId, { error: 'template_apply_failed' }))
  }

  const activeProfileIds = new Set((activeProfiles ?? []).map((row) => row.id as string))
  const shiftsToInsert = applyTemplateToCycle(templateData, cycleStartDate, activeProfileIds).map(
    (row) => ({
      cycle_id: cycleId,
      ...row,
    })
  )
  const skippedCount = templateData.length - shiftsToInsert.length

  const insertResult = await insertAutoGeneratedShifts(supabase as never, shiftsToInsert)
  if (insertResult.error && !insertResult.duplicateConflict) {
    redirect(buildCoverageUrl(cycleId, { error: 'template_apply_failed' }))
  }

  revalidatePath('/coverage')
  revalidatePath('/schedule')

  redirect(
    buildCoverageUrl(cycleId, {
      success: 'template_applied',
      imported: String(insertResult.insertedCount),
      skipped: skippedCount > 0 ? String(skippedCount) : undefined,
    })
  )
}
